version: '3.9'

services:

  pharmacy_service:
    restart: on-failure
    container_name: pharmacy_service
    build: pharmacy_service/
    ports:
      - "8000:80"

  pharmacy_api_service:
    restart: on-failure
    container_name: pharmacy_api_service
    build: pharmacy_api_service/
    ports:
      - "8001:80"
